---
    name: 06. Condition 1
    on: workflow_dispatch
    jobs:
      build:
        if: github.repository == 'imseonghoon/github-action'
        runs-on: ubuntu-latest
        steps:
        - name: Step 1
          run: |
            echo "Run Step 1, Say Hello imseonghoon"
        - name: Step 2
          if: github.event_name == 'workflow_dispatch'
          run: |
            echo "Run Step 2, Say Hello github-action"
        
  